version: '3.8'

services:
  larachat-app:
    build:
      context: '.'
      args:
        uid: 1000
    container_name: larachat-app
    ports:
      - 5050:80
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - .:/var/www/html
    networks:
      backend:
        aliases:
          - larachat-app

  mysql-larachat:
    image: mysql:5.7
    container_name: mysql-larachat
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      backend:
        aliases:
          - mysql-larachat

networks:
  backend:
    name: larachat-network